AWSTemplateFormatVersion: 2010-09-09
Resources:
  Windows2016:
    Type: AWS::EC2::Instance
    Metadata: 
        AWS::CloudFormation::Init: 
           configSets:
             default:
              - rename
           rename:
                 commands:
                   1newname:
                     command: !Sub |
                       powershell.exe -Command Rename-Computer -NewName ${InstName} -Force -Restart"
                       waitAfterCompletion: forever
                   2installreqs:
                     command: powershell.exe -Command Add-WindowsFeature AD-Domain-Services, RSAT-AD-AdminCenter,RSAT-ADDS-Tools -LogPath "C:\Logs.txt"
                     waitAfterCompletion: 60
                   3dcpromo:
                     command: !Sub |
                       powershell.exe -Command Install-ADDSForest -DomainName ${DomainName} -DomainMode default -InstallDns -SafeModeAdministratorPassword (ConvertTo-SecureString ${AdminPwd} -AsPlainText -Force) -Confirm:$false -Force
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      Tags:
         - Key: "Name"
           Value: !Ref InstName
         
         - Key: "Test"
           Value: "Yes"
      SecurityGroupIds:
        - sg-034bff1e03e89cf79
        - sg-09b16a3c92b4b7f71
      UserData:
        'Fn::Base64': 
          !Sub |
          # Install the files and packages from the metadata
           <script> cfn-init.exe -v --stack ${AWS::StackId} --configsets default --resource Windows2016  --region ${AWS::Region} </script>
Parameters:
  InstanceType:
    Description: Windows 2016 Server
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: AWS_KEY3
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  ImageId:
    Description: Image ID
    Type: String
    Default: ami-050202fb72f001b47
  InstName:
    Description: Value of Name tag
    Type: String
  DomainName:
    Description: FQDN of new domain
    Type: String
  AdminPwd:
    Description: Password for Administrator account
    Type: String

