AWSTemplateFormatVersion: 2010-09-09
Resources:
  Windows2016:
    Type: AWS::EC2::Instance
    Metadata: 
        AWS::CloudFormation::Init: 
         commands:
           rename:
                command: "powershell.exe -Command Rename-Computer -NewName !Ref InstName"
                waitAfterCompletion: "forever"
           InstPre:
                command: "powershell.exe -Command Add-WindowsFeature AD-Domain-Services, RSAT-AD-AdminCenter,RSAT-ADDS-Tools"
                waitAfterCompletion: "forever"
           CreateDC:
                command: "powershell.exe -Command Install-ADDSForest -DomainName !Ref DomainName -DomainMode default -InstallDns -SafeModeAdministratorPassword (ConvertTo-SecureString !Ref AdminPwd -AsPlainText -Force) -Confirm:$false -Force"
                waitAfterCompletion: "forever"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: "Instance_S3_Bucket_Full"
      Tags:
         - Key: "Name"
           Value: !Ref InstName
         
         - Key: "Test"
           Value: "Yes"
      SecurityGroupIds:
        - sg-034bff1e03e89cf79
      UserData:
        'Fn::Base64': 
          !Sub |
          # Install the files and packages from the metadata
            cfn-init.exe -v --stack ${AWS::StackName} --resource EC2Instance  --region ${AWS::Region}  
Parameters:
  InstanceType:
    Description: Windows 2016 Server
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: AWS_KEY3
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  ImageId:
    Description: Image ID
    Type: String
    Default: ami-050202fb72f001b47
  InstName:
    Description: Value of Name tag
    Type: String
  DomainName:
    Description: FQDN of new domain
    Type: String
  AdminPwd:
    Description: Password for Administrator account
    Type: String