AWSTemplateFormatVersion: 2010-09-09
Description: Create Security group allowing SSH access
Resources:
    SSHSG:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow inbound Port 443 from app server
            GroupName: !Ref GroupName
            VpcId: vpc-04145030a5e37427f
            Tags:
               - Key: "Name"
                 Value: !Ref GroupName
            SecurityGroupIngress:
            - IpProtocol: tcp
              ToPort: 443
              FromPort: 443
              CidrIp: !Ref Appserver
Parameters:
    GroupName:
       Description: Name of Security Group
       Type: String
    Appserver:
        Description: IP address of App server connecting on port 1521 to this instance
        Type: String
        Default: 10.102.2.247/32
