AWSTemplateFormatVersion: 2010-09-09
Resources:
  ubuntu1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: 'Instance_S3_Bucket_Full'
      SubnetId: !Ref SubnetID
      SecurityGroupIds:
        - sg-009d8beb228c3ac60
        - sg-0b348a2a9adb71e06
      Tags:
        - Key: Name
          Value: !Ref NameTag
      UserData:
        Fn::Base64: !Sub |
              #!/bin/bash
              sudo apt update
              sudo apt-get -y install python-pip
              sudo pip install --upgrade pip
              sudo pip install awscli
              sudo apt upgrade -y
Parameters:
  InstanceType:
    Description: Instance Type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  ImageId:
    Description: Image ID
    Type: String
    Default: ami-026c8acd92718196b
  SubnetID:
    Description: Subnet for the instance
    Type: String
    Default: subnet-0de453bb373cc9854
  NameTag:
    Description: Name tag value
    Type: String
