AWSTemplateFormatVersion: 2010-09-09
Resources:
  Windows2016:
    Type: AWS::EC2::Instance
    Metadata: 
        AWS::CloudFormation::Init: 
           configSets:
             default:
              - rename
           rename:
                 commands:
                   1newname:
                     command: !Sub |
                       powershell.exe -Command Rename-Computer -NewName ${InstName} -Force -Restart
                       waitAfterCompletion: forever
                   2installreqs:
                     command: powershell.exe -Command Add-WindowsFeature AD-Domain-Services, RSAT-AD-AdminCenter,RSAT-ADDS-Tools -LogPath "C:\Logs.txt"
                     waitAfterCompletion: 60
                   3timezone:
                     command: powershell.exe -Command  Set-TimeZone -Name "Eastern Standard Time"                
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetID
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      Tags:
         - Key: "Name"
           Value: !Ref InstName
      UserData:
        'Fn::Base64': 
          !Sub |
          # Install the files and packages from the metadata
           <script> cfn-init.exe -v --stack ${AWS::StackId} --configsets default --resource Windows2016  --region ${AWS::Region} </script>
      SsmAssociations: 
      - 
        DocumentName: "AWS-JoinDirectoryServiceDomain"
        AssociationParameters: 
          - 
            Key: "directoryId"
            Value: 
              - 
                Ref: "directoryId"
          - 
            Key: "directoryName"
            Value: 
              -
                Ref: "myDirectory"              
Parameters:
  InstanceType:
    Description: Windows 2016 Server
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: AWS_KEY3
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  ImageId:
    Description: Image ID
    Type: String
    Default: ami-050202fb72f001b47
  InstName:
    Description: Value of Name tag
    Type: String
  SubnetID:
    Description: Subnet for the instance
    Type: String
    Default: subnet-07221e27b08b06428
  directoryId:
    Description: Directory ID 
    Type: String
  myDirectory:
    Description: Directory Name
    Type: String