AWSTemplateFormatVersion: 2010-09-09
Description: Create Security group for DB servers
Resources:
    DBserverSG:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow Connection to DB servers
            GroupName: !Ref GroupName
            VpcId: vpc-04145030a5e37427f
            Tags:
               - Key: "Name"
                 Value: !Ref GroupName
            SecurityGroupIngress:
            - IpProtocol: tcp
              ToPort: 1521
              FromPort: 1521
              CidrIp: !Ref DBserver
            - IpProtocol: tcp
              ToPort: 1521
              FromPort: 1521
              CidrIp: !Ref TBserver
            - IpProtocol: tcp
              ToPort: 1521
              FromPort: 1521
              CidrIp: !Ref SharedBas
Parameters:
    GroupName:
       Description: Name of Security Group
       Type: String
    DBserver:
        Description: IP address of App server connecting on port 1521 to this instance
        Type: String
        Default: 10.102.2.109/32
    TBserver:
        Description: IP address of Tableau server connecting on port 1521 to this instance
        Type: String
        Default: 10.102.2.133/32
    SharedBas:
        Description: IP address of Shared Svc Bastion server connecting on port 1521 to this instance
        Type: String
        Default: 10.25.0.102/32
    