AWSTemplateFormatVersion: 2010-09-09
Description: Create AWS Linux server on sharedsvc private subnet
Resources:
  LinuxServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: 'AmazonEC2RoleforSSM'
      SubnetId: !Ref SubnetID
      Tags:
         - Key: "Name"
           Value: !Ref HostName
         
         - Key: "Environment"
           Value: "SharedSVC"
      SecurityGroupIds:
        - !Ref SGID
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash
           hostnamectl set-hostname "${HostName}"
           hostnamectl set-hostname --transient "${HostName}"
           sudo yum -y install sssd realmd krb5-workstation samba-common-tools
Parameters:
  InstanceType:
    Description: Instance Type
    Type: String
    Default: t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  ImageId:
    Description: Image ID
    Type: String
    Default: ami-0b898040803850657
  SubnetID:
    Description: Subnet for the instance
    Type: String
    Default: subnet-00914a752c073aa7f
  SGID:
    Description: Security Group
    Type: String
    Default: sg-091de8cc8755a3781
  HostName:
    Description: Hostname of Instance
    Type: String

